<?php
/**
 * Performance Toolkit – Advanced Cache Drop-in
 *
 * Installed at wp-content/advanced-cache.php on plugin activation.
 * Serves static HTML files before WordPress fully loads.
 *
 * DO NOT EDIT – this file is regenerated by the Performance Toolkit plugin.
 *
 * @package PerformanceToolkit
 */

if ( ! defined( 'ABSPATH' ) ) {
	return;
}

// Only handle anonymous GET requests.
if ( ! isset( $_SERVER['REQUEST_METHOD'] ) || 'GET' !== strtoupper( $_SERVER['REQUEST_METHOD'] ) ) {
	return;
}

// Skip CLI and cron.
if ( ( defined( 'WP_CLI' ) && WP_CLI ) || ( defined( 'DOING_CRON' ) && DOING_CRON ) ) {
	return;
}

// Skip logged-in users by checking WP auth cookies.
foreach ( array_keys( $_COOKIE ) as $ptk_cookie ) {
	if ( 0 === strncmp( $ptk_cookie, 'wordpress_logged_in_', 20 ) ) {
		return;
	}
}

// Read plugin config (written by PageCache on settings save / activation).
$ptk_config_file = WP_CONTENT_DIR . '/cache/performance-toolkit/config.php';

if ( ! is_file( $ptk_config_file ) ) {
	return;
}

$ptk_config = include $ptk_config_file;

if ( empty( $ptk_config['enabled'] ) ) {
	return;
}

$ptk_bypass_cookies = isset( $ptk_config['bypass_cookies'] ) && is_array( $ptk_config['bypass_cookies'] )
	? $ptk_config['bypass_cookies']
	: array();

if ( array() !== $ptk_bypass_cookies && isset( $_COOKIE ) && is_array( $_COOKIE ) ) {
	foreach ( array_keys( $_COOKIE ) as $ptk_cookie_name ) {
		if ( ! is_string( $ptk_cookie_name ) || '' === $ptk_cookie_name ) {
			continue;
		}

		foreach ( $ptk_bypass_cookies as $ptk_rule ) {
			$ptk_rule = trim( (string) $ptk_rule );

			if ( '' === $ptk_rule ) {
				continue;
			}

			if ( false !== strpos( $ptk_rule, '*' ) ) {
				if ( fnmatch( $ptk_rule, $ptk_cookie_name ) ) {
					return;
				}

				continue;
			}

			if ( 0 === strcasecmp( $ptk_rule, $ptk_cookie_name ) ) {
				return;
			}
		}
	}
}

$ptk_ttl       = isset( $ptk_config['ttl'] ) ? (int) $ptk_config['ttl'] : 3600;
$ptk_cache_dir = WP_CONTENT_DIR . '/cache/performance-toolkit';
$ptk_scheme    = ( ! empty( $_SERVER['HTTPS'] ) && strtolower( (string) $_SERVER['HTTPS'] ) !== 'off' ) ? 'https' : 'http';
$ptk_host      = isset( $_SERVER['HTTP_HOST'] ) ? (string) $_SERVER['HTTP_HOST'] : 'localhost';
$ptk_uri       = isset( $_SERVER['REQUEST_URI'] ) ? (string) $_SERVER['REQUEST_URI'] : '/';
$ptk_key       = md5( $ptk_scheme . '://' . $ptk_host . $ptk_uri );
$ptk_file      = $ptk_cache_dir . '/' . $ptk_key . '.html';

if ( ! is_file( $ptk_file ) ) {
	return;
}

// Expire stale files.
if ( ( (int) filemtime( $ptk_file ) + $ptk_ttl ) < time() ) {
	@unlink( $ptk_file );
	return;
}

header( 'X-PTK-Cache: HIT' );
header( 'X-Performance-Toolkit-Cache: HIT' );
readfile( $ptk_file );
exit;
