<?php
/**
 * Object cache drop-in manager.
 *
 * Handles installation, removal, and status detection of the
 * file-based object-cache.php drop-in.
 *
 * @package PerformanceToolkit
 */

declare(strict_types=1);

namespace PerformanceToolkit\Cache;

final class ObjectCacheManager {

	/**
	 * Signature string that identifies our own drop-in.
	 * Must also appear verbatim in includes/Cache/object-cache.php.
	 */
	private const SIGNATURE = 'Generated by: WP Performance Toolkit';

	private string $dropin_source;
	private string $dropin_dest;
	private string $cache_dir;

	public function __construct() {
		$this->dropin_source = PERFORMANCE_TOOLKIT_PATH . 'includes/Cache/object-cache.php';
		$this->dropin_dest   = WP_CONTENT_DIR . '/object-cache.php';
		$this->cache_dir     = WP_CONTENT_DIR . '/cache/performance-toolkit/object-cache';
	}

	// -------------------------------------------------------------------------
	// Status detection
	// -------------------------------------------------------------------------

	/**
	 * True if ANY object-cache.php drop-in exists in wp-content.
	 */
	public function isDropinInstalled(): bool {
		return file_exists( $this->dropin_dest );
	}

	/**
	 * True if the installed drop-in was placed by this plugin.
	 */
	public function isOurDropin(): bool {
		if ( ! file_exists( $this->dropin_dest ) ) {
			return false;
		}

		$contents = (string) file_get_contents( $this->dropin_dest );
		return str_contains( $contents, self::SIGNATURE );
	}

	/**
	 * True if a drop-in exists but was NOT installed by us.
	 */
	public function hasForeignDropin(): bool {
		return $this->isDropinInstalled() && ! $this->isOurDropin();
	}

	/**
	 * True if we can install the drop-in (content dir is writable and no foreign drop-in).
	 */
	public function canInstall(): bool {
		return ! $this->hasForeignDropin()
			&& is_writable( WP_CONTENT_DIR )
			&& file_exists( $this->dropin_source );
	}

	/**
	 * Detect the object-cache provider label for display.
	 */
	public function detectProvider(): string {
		if ( $this->isOurDropin() ) {
			return __( 'PTK File Cache', 'performance-toolkit' );
		}

		if ( defined( 'WP_REDIS_CLUSTER' ) ) {
			return 'Redis Cluster';
		}

		// Only report Redis when Redis host is explicitly configured.
		if ( defined( 'WP_REDIS_HOST' ) && '' !== (string) constant( 'WP_REDIS_HOST' ) ) {
			return 'Redis';
		}

		if ( class_exists( 'Memcached' ) || class_exists( 'Memcache' ) ) {
			return 'Memcached';
		}

		if ( $this->isDropinInstalled() ) {
			return __( 'External (unknown)', 'performance-toolkit' );
		}

		return __( 'None', 'performance-toolkit' );
	}

	// -------------------------------------------------------------------------
	// Install / remove
	// -------------------------------------------------------------------------

	/**
	 * Copy the drop-in source file into wp-content/object-cache.php.
	 *
	 * @return array{ok: bool, message: string}
	 */
	public function install(): array {
		if ( $this->hasForeignDropin() ) {
			return array(
				'ok'      => false,
				'message' => __( 'Another plugin already manages object-cache.php. Performance Toolkit did not overwrite it.', 'performance-toolkit' ),
			);
		}

		if ( ! file_exists( $this->dropin_source ) ) {
			return array(
				'ok'      => false,
				'message' => __( 'The object-cache source file is missing from the plugin directory.', 'performance-toolkit' ),
			);
		}

		if ( ! is_writable( WP_CONTENT_DIR ) ) {
			return array(
				'ok'      => false,
				'message' => __( 'The wp-content directory is not writable by PHP.', 'performance-toolkit' ),
			);
		}

		$copied = copy( $this->dropin_source, $this->dropin_dest );

		if ( ! $copied ) {
			return array(
				'ok'      => false,
				'message' => __( 'PHP failed to copy object-cache.php into wp-content.', 'performance-toolkit' ),
			);
		}

		return array(
			'ok'      => true,
			'message' => __( 'File-based object cache enabled. Changes take effect on next page load.', 'performance-toolkit' ),
		);
	}

	/**
	 * Remove the drop-in if it is ours.
	 *
	 * @return array{ok: bool, message: string}
	 */
	public function remove(): array {
		if ( ! $this->isOurDropin() ) {
			return array(
				'ok'      => false,
				'message' => __( 'The installed object-cache.php was not placed by Performance Toolkit.', 'performance-toolkit' ),
			);
		}

		if ( ! unlink( $this->dropin_dest ) ) {
			return array(
				'ok'      => false,
				'message' => __( 'Could not remove object-cache.php. Please check file permissions.', 'performance-toolkit' ),
			);
		}

		return array(
			'ok'      => true,
			'message' => __( 'File-based object cache disabled. Changes take effect on next page load.', 'performance-toolkit' ),
		);
	}

	// -------------------------------------------------------------------------
	// Cache stats
	// -------------------------------------------------------------------------

	/**
	 * @return array{entry_count: int, size_bytes: int, size_formatted: string}
	 */
	public function getStats(): array {
		if ( ! is_dir( $this->cache_dir ) ) {
			return array(
				'entry_count'    => 0,
				'size_bytes'     => 0,
				'size_formatted' => '0 B',
			);
		}

		$count = 0;
		$size  = 0;

		foreach ( glob( $this->cache_dir . '/*', GLOB_ONLYDIR ) ?: array() as $group_dir ) {
			foreach ( glob( $group_dir . '/*.php' ) ?: array() as $file ) {
				++$count;
				$size += (int) @filesize( $file );
			}
		}

		return array(
			'entry_count'    => $count,
			'size_bytes'     => $size,
			'size_formatted' => $this->formatBytes( $size ),
		);
	}

	/**
	 * Delete all files inside the object cache directory.
	 *
	 * @return array{ok: bool, message: string}
	 */
	public function flush(): array {
		if ( ! is_dir( $this->cache_dir ) ) {
			return array(
				'ok'      => true,
				'message' => __( 'Object cache is empty.', 'performance-toolkit' ),
			);
		}

		$count = 0;
		foreach ( glob( $this->cache_dir . '/*', GLOB_ONLYDIR ) ?: array() as $group_dir ) {
			foreach ( glob( $group_dir . '/*.php' ) ?: array() as $file ) {
				if ( @unlink( $file ) ) {
					++$count;
				}
			}
		}

		// Also call the live WP function so in-memory entries are cleared.
		if ( function_exists( 'wp_cache_flush' ) ) {
			wp_cache_flush();
		}

		return array(
			'ok'      => true,
			/* translators: %d: number of cache entries deleted. */
			'message' => sprintf( __( 'Object cache flushed. %d entries removed.', 'performance-toolkit' ), $count ),
		);
	}

	// -------------------------------------------------------------------------
	// Helpers
	// -------------------------------------------------------------------------

	private function formatBytes( int $bytes ): string {
		if ( $bytes >= 1048576 ) {
			return number_format( $bytes / 1048576, 2 ) . ' MB';
		}

		if ( $bytes >= 1024 ) {
			return number_format( $bytes / 1024, 2 ) . ' KB';
		}

		return $bytes . ' B';
	}
}
