<?php
/**
 * Pivot Performance Toolkit - File-Based Object Cache Drop-in
 * Generated by: Pivot Performance Toolkit
 *
 * DO NOT EDIT - this file is managed by the Pivot Performance Toolkit plugin.
 *
 * @package PivotPerformanceToolkit
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// phpcs:disable WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
// phpcs:disable WordPress.WP.AlternativeFunctions.file_system_operations_file_get_contents
// phpcs:disable WordPress.PHP.NoSilencedErrors.Discouraged
// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedFunctionFound -- wp_cache_get(), wp_cache_set(), etc. are WordPress core's own Object Cache API function names; WP core and every other plugin call them by this exact literal name, so they cannot be prefixed without breaking the entire object cache system.

if ( ! class_exists( 'WP_Object_Cache' ) ) {
	/**
	 * File-based persistent object cache.
	 */
	class WP_Object_Cache {
		/** @var array<string, array<string, mixed>> */
		private array $cache = array();

		/** @var string[] */
		private array $global_groups = array();

		/** @var string[] */
		private array $non_persistent_groups = array();

		private string $cache_dir;

		private int $cache_hits = 0;

		private int $cache_misses = 0;

		public function __construct() {
			$this->cache_dir = WP_CONTENT_DIR . '/cache/pivot-performance-toolkit/object-cache';

			if ( ! is_dir( $this->cache_dir ) ) {
				// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir -- this object-cache drop-in runs on every request type (frontend, AJAX, REST, cron), not just admin; WP_Filesystem lives in wp-admin/includes/file.php (not loaded here) and its init can itself prompt for credentials, which would be unsafe to trigger from a hot cache path.
				@mkdir( $this->cache_dir, 0755, true );
			}

			/*
			 * WordPress caches every autoloaded option together as a single
			 * "alloptions" blob and updates it with a read-modify-write:
			 * load the current blob, patch in the one changed option,
			 * write the whole blob back. That sequence isn't atomic across
			 * processes here — any other concurrent request that updates a
			 * *different* autoloaded option (most commonly WP-Cron's own
			 * "cron" option, re-saved via the loopback request fired after
			 * almost every page load) can read a stale blob and write it
			 * back whole, silently reverting an option that was correctly
			 * saved to the database moments earlier. Keeping "options"
			 * non-persistent avoids the cross-process race entirely by
			 * always rebuilding it fresh from the database (single source
			 * of truth) each request, at the cost of one extra query.
			 */
			$this->non_persistent_groups[] = 'options';
		}

		/**
		 * @param mixed  $key
		 * @param mixed  $data
		 * @param string $group
		 */
		public function add( $key, $data, $group = 'default', $expire = 0 ): bool {
			$group_key = $this->normalize_group( (string) $group );
			$cache_key = $this->normalize_key( $key );

			if ( array_key_exists( $cache_key, $this->cache[ $group_key ] ?? array() ) ) {
				return false;
			}

			$found = false;
			$this->get( $key, $group_key, false, $found );
			if ( $found ) {
				return false;
			}

			return $this->set( $key, $data, $group_key, (int) $expire );
		}

		/**
		 * @param mixed $key
		 * @param mixed $data
		 */
		public function set( $key, $data, $group = 'default', $expire = 0 ): bool {
			$group_key = $this->normalize_group( (string) $group );
			$cache_key = $this->normalize_key( $key );
			$this->cache[ $group_key ][ $cache_key ] = $data;

			if ( in_array( $group_key, $this->non_persistent_groups, true ) ) {
				return true;
			}

			return $this->write_file( $group_key, $cache_key, $data, (int) $expire );
		}

		/**
		 * @param mixed      $key
		 * @param bool|null &$found
		 * @return mixed|false
		 */
		public function get( $key, $group = 'default', $force = false, &$found = null ) {
			$group_key = $this->normalize_group( (string) $group );
			$cache_key = $this->normalize_key( $key );

			if ( ! $force && array_key_exists( $cache_key, $this->cache[ $group_key ] ?? array() ) ) {
				++$this->cache_hits;
				$found = true;
				return $this->cache[ $group_key ][ $cache_key ];
			}

			if ( in_array( $group_key, $this->non_persistent_groups, true ) ) {
				++$this->cache_misses;
				$found = false;
				return false;
			}

			$data = $this->read_file( $group_key, $cache_key );
			if ( false === $data ) {
				++$this->cache_misses;
				$found = false;
				return false;
			}

			++$this->cache_hits;
			$found = true;
			$this->cache[ $group_key ][ $cache_key ] = $data;

			return $data;
		}

		/**
		 * @param mixed $key
		 */
		public function replace( $key, $data, $group = 'default', $expire = 0 ): bool {
			$found = false;
			$this->get( $key, $group, false, $found );
			if ( ! $found ) {
				return false;
			}

			return $this->set( $key, $data, $group, (int) $expire );
		}

		/**
		 * @param mixed $key
		 */
		public function delete( $key, $group = 'default' ): bool {
			$group_key = $this->normalize_group( (string) $group );
			$cache_key = $this->normalize_key( $key );
			unset( $this->cache[ $group_key ][ $cache_key ] );

			if ( in_array( $group_key, $this->non_persistent_groups, true ) ) {
				return true;
			}

			$file = $this->file_path( $group_key, $cache_key );
			if ( ! file_exists( $file ) ) {
				return true;
			}

			if ( function_exists( 'opcache_invalidate' ) ) {
				opcache_invalidate( $file, true );
			}

			return (bool) wp_delete_file( $file );
		}

		public function flush(): bool {
			$this->cache = array();
			$this->delete_dir( $this->cache_dir );
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir -- this object-cache drop-in runs on every request type (frontend, AJAX, REST, cron), not just admin; WP_Filesystem lives in wp-admin/includes/file.php (not loaded here) and its init can itself prompt for credentials, which would be unsafe to trigger from a hot cache path.
			@mkdir( $this->cache_dir, 0755, true );
			return true;
		}

		public function flush_group( string $group ): bool {
			$group_key = $this->normalize_group( $group );
			unset( $this->cache[ $group_key ] );

			$group_dir = $this->cache_dir . '/' . $group_key;
			if ( is_dir( $group_dir ) ) {
				$this->delete_dir( $group_dir );
			}

			return true;
		}

		public function flush_runtime(): bool {
			$this->cache = array();
			return true;
		}

		/**
		 * @param mixed $key
		 * @return int|false
		 */
		public function incr( $key, $offset = 1, $group = 'default' ) {
			$value = $this->get( $key, $group );
			if ( false === $value ) {
				return false;
			}

			$value = max( 0, (int) $value + (int) $offset );
			$this->set( $key, $value, $group );
			return $value;
		}

		/**
		 * @param mixed $key
		 * @return int|false
		 */
		public function decr( $key, $offset = 1, $group = 'default' ) {
			$value = $this->get( $key, $group );
			if ( false === $value ) {
				return false;
			}

			$value = max( 0, (int) $value - (int) $offset );
			$this->set( $key, $value, $group );
			return $value;
		}

		/**
		 * @param string|string[] $groups
		 */
		public function add_global_groups( $groups ): void {
			foreach ( (array) $groups as $group ) {
				$group = (string) $group;
				if ( ! in_array( $group, $this->global_groups, true ) ) {
					$this->global_groups[] = $group;
				}
			}
		}

		/**
		 * @param string|string[] $groups
		 */
		public function add_non_persistent_groups( $groups ): void {
			foreach ( (array) $groups as $group ) {
				$group = (string) $group;
				if ( ! in_array( $group, $this->non_persistent_groups, true ) ) {
					$this->non_persistent_groups[] = $group;
				}
			}
		}

		public function close(): bool {
			return true;
		}

		public function stats(): void {
			/* translators: %d: number of cache hits. */
			echo '<p>' . esc_html( sprintf( __( 'Cache hits: %d', 'pivot-performance-toolkit' ), $this->cache_hits ) ) . '<br />';
			/* translators: %d: number of cache misses. */
			echo esc_html( sprintf( __( 'Cache misses: %d', 'pivot-performance-toolkit' ), $this->cache_misses ) ) . '</p>';
		}

		private function normalize_group( string $group ): string {
			return '' === $group ? 'default' : $group;
		}

		/**
		 * @param mixed $key
		 */
		private function normalize_key( $key ): string {
			return md5( (string) $key );
		}

		private function file_path( string $group, string $cache_key ): string {
			return $this->cache_dir . '/' . $group . '/' . $cache_key . '.php';
		}

		/**
		 * @param mixed $data
		 */
		private function write_file( string $group, string $cache_key, $data, int $expire ): bool {
			$group_dir = $this->cache_dir . '/' . $group;
			if ( ! is_dir( $group_dir ) ) {
				// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir -- this object-cache drop-in runs on every request type (frontend, AJAX, REST, cron), not just admin; WP_Filesystem lives in wp-admin/includes/file.php (not loaded here) and its init can itself prompt for credentials, which would be unsafe to trigger from a hot cache path.
				@mkdir( $group_dir, 0755, true );
			}

			$expires_at = $expire > 0 ? ( time() + $expire ) : 0;
			$payload    = array(
				'e' => $expires_at,
				'd' => $data,
			);

			// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export -- not debug output: this is the object-cache's storage format, a PHP-file cache (`<?php return array(...);`) included directly for fast, opcache-friendly reads.
			$raw  = '<?php return ' . var_export( $payload, true ) . ';';
			$path = $this->file_path( $group, $cache_key );

			$written = false !== @file_put_contents( $path, $raw, LOCK_EX );

			/*
			 * Every write overwrites this same file in place for its cache
			 * key. Without forcing invalidation, opcache can keep serving a
			 * previously-compiled version of this exact path for up to
			 * opcache.revalidate_freq seconds (default 2s) — e.g. a
			 * password change written here can still read back as the old
			 * hash for a couple of seconds, causing intermittent login
			 * failures right after a legitimate update.
			 */
			if ( $written && function_exists( 'opcache_invalidate' ) ) {
				opcache_invalidate( $path, true );
			}

			return $written;
		}

		/**
		 * @return mixed|false
		 */
		private function read_file( string $group, string $cache_key ) {
			$file = $this->file_path( $group, $cache_key );
			if ( ! file_exists( $file ) ) {
				return false;
			}

			$payload = include $file;
			if ( ! is_array( $payload ) || ! array_key_exists( 'd', $payload ) ) {
				return false;
			}

			$expires_at = (int) ( $payload['e'] ?? 0 );
			if ( $expires_at > 0 && $expires_at < time() ) {
				wp_delete_file( $file );
				return false;
			}

			return $payload['d'];
		}

		private function delete_dir( string $dir ): void {
			if ( ! is_dir( $dir ) ) {
				return;
			}

			$items = glob( $dir . '/*' ) ?: array();
			foreach ( $items as $item ) {
				if ( is_dir( $item ) ) {
					$this->delete_dir( $item );
				} else {
					wp_delete_file( $item );
				}
			}

			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir -- this object-cache drop-in runs on every request type (frontend, AJAX, REST, cron), not just admin; WP_Filesystem lives in wp-admin/includes/file.php (not loaded here) and its init can itself prompt for credentials, which would be unsafe to trigger from a hot cache path.
			@rmdir( $dir );
		}
	}
}

/** @global WP_Object_Cache $wp_object_cache */
function wp_cache_init(): void {
	global $wp_object_cache;
	$wp_object_cache = new WP_Object_Cache();
}

/**
 * @param mixed $key
 * @param mixed $data
 */
function wp_cache_add( $key, $data, $group = '', $expire = 0 ): bool {
	global $wp_object_cache;
	return $wp_object_cache->add( $key, $data, $group, (int) $expire );
}

/**
 * @param array<string, mixed> $data
 * @return array<string, bool>
 */
function wp_cache_add_multiple( array $data, $group = '', $expire = 0 ): array {
	global $wp_object_cache;
	$results = array();
	foreach ( $data as $key => $value ) {
		$results[ (string) $key ] = wp_cache_add( $key, $value, $group, $expire );
	}
	return $results;
}

/**
 * @param mixed $key
 * @param mixed $data
 */
function wp_cache_set( $key, $data, $group = '', $expire = 0 ): bool {
	global $wp_object_cache;
	return $wp_object_cache->set( $key, $data, $group, (int) $expire );
}

/**
 * @param array<string, mixed> $data
 * @return array<string, bool>
 */
function wp_cache_set_multiple( array $data, $group = '', $expire = 0 ): array {
	global $wp_object_cache;
	$results = array();
	foreach ( $data as $key => $value ) {
		$results[ (string) $key ] = $wp_object_cache->set( $key, $value, $group, (int) $expire );
	}
	return $results;
}

/**
 * @param mixed $key
 * @param bool|null &$found
 * @return mixed|false
 */
function wp_cache_get( $key, $group = '', $force = false, &$found = null ) {
	global $wp_object_cache;
	return $wp_object_cache->get( $key, $group, $force, $found );
}

/**
 * @param string[] $keys
 * @return array<string, mixed>
 */
function wp_cache_get_multiple( array $keys, $group = '', $force = false ): array {
	global $wp_object_cache;
	$results = array();
	foreach ( $keys as $key ) {
		$results[ (string) $key ] = $wp_object_cache->get( $key, $group, $force );
	}
	return $results;
}

/**
 * @param mixed $key
 */
function wp_cache_replace( $key, $data, $group = '', $expire = 0 ): bool {
	global $wp_object_cache;
	return $wp_object_cache->replace( $key, $data, $group, (int) $expire );
}

/**
 * @param mixed $key
 */
function wp_cache_delete( $key, $group = '' ): bool {
	global $wp_object_cache;
	return $wp_object_cache->delete( $key, $group );
}

/**
 * @param string[] $keys
 * @return array<string, bool>
 */
function wp_cache_delete_multiple( array $keys, $group = '' ): array {
	global $wp_object_cache;
	$results = array();
	foreach ( $keys as $key ) {
		$results[ (string) $key ] = $wp_object_cache->delete( $key, $group );
	}
	return $results;
}

function wp_cache_flush(): bool {
	global $wp_object_cache;
	return $wp_object_cache->flush();
}

function wp_cache_flush_group( string $group ): bool {
	global $wp_object_cache;
	return $wp_object_cache->flush_group( $group );
}

function wp_cache_flush_runtime(): bool {
	global $wp_object_cache;
	return $wp_object_cache->flush_runtime();
}

/**
 * @param mixed $key
 * @return int|false
 */
function wp_cache_incr( $key, $offset = 1, $group = '' ) {
	global $wp_object_cache;
	return $wp_object_cache->incr( $key, (int) $offset, $group );
}

/**
 * @param mixed $key
 * @return int|false
 */
function wp_cache_decr( $key, $offset = 1, $group = '' ) {
	global $wp_object_cache;
	return $wp_object_cache->decr( $key, (int) $offset, $group );
}

/**
 * @param string|string[] $groups
 */
function wp_cache_add_global_groups( $groups ): void {
	global $wp_object_cache;
	$wp_object_cache->add_global_groups( $groups );
}

/**
 * @param string|string[] $groups
 */
function wp_cache_add_non_persistent_groups( $groups ): void {
	global $wp_object_cache;
	$wp_object_cache->add_non_persistent_groups( $groups );
}

function wp_cache_close(): bool {
	return true;
}

function wp_cache_stats(): void {
	global $wp_object_cache;
	$wp_object_cache->stats();
}

